version: '3.8'

services:
  web:
    build: .
    container_name: web-security-cam
    ports:
      - "5030:5000"
    volumes:
      - ./public:/app/public
      - ./public/audio:/app/public/audio
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production 